#plugin 'cocoapods-binary'

use_frameworks!
#all_binary!
platform :ios, '9.0'

target 'HelloPodTest_Example' do
  pod 'HelloPodTest', :path => '../'
#  pod 'HelloPodTest', :git => 'git@github.com:CLJian/TestPodConfig.git'
  pod 'AFNetworking'

  target 'HelloPodTest_Tests' do
    inherit! :search_paths

    
  end
end
